# Generated by Django 6.0.6 on 2026-07-22 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adddepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=225)),
                ('department_code', models.CharField(max_length=20)),
                ('dep_head', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('dep_email', models.CharField(max_length=100)),
                ('dep_number', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='addemployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('username', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('empid', models.IntegerField()),
                ('department', models.CharField(max_length=500)),
                ('designation', models.CharField(max_length=225)),
                ('role', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=16)),
                ('photo', models.ImageField(upload_to='profile/')),
                ('address', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='adminlogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=225)),
                ('password', models.CharField(max_length=16)),
                ('create_add', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fileupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_no', models.CharField(max_length=100, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('priority', models.CharField(max_length=50)),
                ('create_user', models.CharField(blank=True, max_length=100, null=True)),
                ('departments', models.CharField(blank=True, max_length=100, null=True)),
                ('current_user', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('description', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='userlogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=225)),
                ('password', models.CharField(max_length=16)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
