# Generated by Django 6.0.6 on 2026-07-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
