# Generated by Django 6.0.6 on 2026-07-23 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_fileupload_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addemployee',
            name='empid',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='addemployee',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
        migrations.CreateModel(
            name='FileMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.CharField(max_length=100)),
                ('to_user', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
                ('moved_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.fileupload')),
            ],
        ),
    ]
