# Generated by Django 6.0.6 on 2026-07-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_addemployee_empid_alter_addemployee_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemovement',
            name='remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
